### ISSUE TITLE
Missing dependency on opentelemetry after upgrade from 1.5.0 -> 1.6.0

### ISSUE THREAD

**Issue by AntonioYuen** [namely/chief-of-state#427]
**Describe the bug**
OpenTelemetry is missing a metrics import
```
 | java.lang.NoClassDefFoundError: io/opentelemetry/proto/collector/metrics/v1/MetricsServiceGrpc
chiefofstate_1  | 	at io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter.<init>(OtlpGrpcMetricExporter.java:47)
chiefofstate_1  | 	at io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporterBuilder.build(OtlpGrpcMetricExporterBuilder.java:129)
chiefofstate_1  | 	at io.superflat.otel.tools.TelemetryTools.configureMetricsExporter(TelemetryTools.scala:47)
chiefofstate_1  | 	at io.superflat.otel.tools.TelemetryTools.start(TelemetryTools.scala:26)
```

**To Reproduce**
  1. Launch COS

**Expected behavior**
COS should not throw a java.lang.NoClassDefFoundError on boot
